//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Giusti.Restaurante.Business.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Giusti.Restaurante.Business.Resource.Mensagem", typeof(Mensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria excluída com sucesso.
        /// </summary>
        internal static string Categoria_ExcluiCategoriaOK {
            get {
                return ResourceManager.GetString("Categoria_ExcluiCategoriaOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria não encontrada.
        /// </summary>
        internal static string Categoria_NaoEncontrada {
            get {
                return ResourceManager.GetString("Categoria_NaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria salva com sucesso.
        /// </summary>
        internal static string Categoria_SalvaCategoriaOK {
            get {
                return ResourceManager.GetString("Categoria_SalvaCategoriaOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesa não encontrada.
        /// </summary>
        internal static string Mesa_NaoEncontrada {
            get {
                return ResourceManager.GetString("Mesa_NaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesa salva com sucesso.
        /// </summary>
        internal static string Mesa_SalvaMesaOK {
            get {
                return ResourceManager.GetString("Mesa_SalvaMesaOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido excluído com sucesso.
        /// </summary>
        internal static string Pedido_ExcluiPedidoOK {
            get {
                return ResourceManager.GetString("Pedido_ExcluiPedidoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido não encontrado.
        /// </summary>
        internal static string Pedido_NaoEncontrado {
            get {
                return ResourceManager.GetString("Pedido_NaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido salvo com sucesso.
        /// </summary>
        internal static string Pedido_SalvaPedidoOK {
            get {
                return ResourceManager.GetString("Pedido_SalvaPedidoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prato excluído com sucesso.
        /// </summary>
        internal static string Prato_ExcluiPratoOK {
            get {
                return ResourceManager.GetString("Prato_ExcluiPratoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prato não encontrado.
        /// </summary>
        internal static string Prato_NaoEncontrado {
            get {
                return ResourceManager.GetString("Prato_NaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prato salvo com sucesso.
        /// </summary>
        internal static string Prato_SalvaPratoOK {
            get {
                return ResourceManager.GetString("Prato_SalvaPratoOK", resourceCulture);
            }
        }
    }
}
